---
apiVersion: v1
kind: Pod
metadata:
        name: twitter-pod
        labels:
                app: twitter-pod
spec:
        containers:
                - name: rest-server
                  image: rest-server:1.0
                  ports:
                          - containerPort: 8888
                - name: backend-server
                  image: backend-server:1.0
                  ports:
                          - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
        name: twitter-service
        labels:
                app: twitter-service
spec:
        type: NodePort
        selector:
                app: twitter-pod
        ports:
                - name: http
                  protocol: TCP
                  targetPort: 8888
                  port: 8888
                  nodePort: 30013
